version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./server/.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_DOCKER_PASSWORD
      - MYSQL_DATABASE=$DB_DOCKER_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  app:
    depends_on:
      - db

    build: ./server
    restart: unless-stopped
    env_file: ./server/.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=db
      - DB_USER=$DB_DOCKER_USER
      - DB_PASSWORD=$DB_DOCKER_PASSWORD
      - DB_NAME=$DB_DOCKER_NAME
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db: